# Generated by Django 5.2 on 2025-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visited_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('visited', 'Visited'), ('want_to_visit', 'Want to Visit')], max_length=20),
        ),
    ]
