# Generated by Django 5.2 on 2025-04-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_rename_visited_at_visit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Country Visit', 'verbose_name_plural': 'Country Visits'},
        ),
    ]
