# Generated by Django 5.2 on 2025-04-29 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_visit_options_visit_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('visited', 'Visited'), ('want_to_visit', 'Want to Visit')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['user', 'status'], name='countries_v_user_id_6c164b_idx'),
        ),
    ]
